# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoTimeConfirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoTimeConfirmWindow(object):
    def setupUi(self, NoTimeConfirmWindow):
        NoTimeConfirmWindow.setObjectName("NoTimeConfirmWindow")
        NoTimeConfirmWindow.resize(500, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NoTimeConfirmWindow.sizePolicy().hasHeightForWidth())
        NoTimeConfirmWindow.setSizePolicy(sizePolicy)
        NoTimeConfirmWindow.setMinimumSize(QtCore.QSize(500, 130))
        NoTimeConfirmWindow.setMaximumSize(QtCore.QSize(500, 130))
        self.gridLayout = QtWidgets.QGridLayout(NoTimeConfirmWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(NoTimeConfirmWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(NoTimeConfirmWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(NoTimeConfirmWindow)
        self.buttonBox.accepted.connect(NoTimeConfirmWindow.accept)
        self.buttonBox.rejected.connect(NoTimeConfirmWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(NoTimeConfirmWindow)

    def retranslateUi(self, NoTimeConfirmWindow):
        _translate = QtCore.QCoreApplication.translate
        NoTimeConfirmWindow.setWindowTitle(_translate("NoTimeConfirmWindow", "Confirm"))
        self.label.setText(_translate("NoTimeConfirmWindow", "是否将此页空白备注的幻灯片在视频中的展示时间设置为0秒？"))
