# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuitWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FinishWindow(object):
    def setupUi(self, FinishWindow):
        FinishWindow.setObjectName("FinishWindow")
        FinishWindow.resize(430, 120)
        FinishWindow.setMinimumSize(QtCore.QSize(430, 120))
        FinishWindow.setMaximumSize(QtCore.QSize(430, 120))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        FinishWindow.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(FinishWindow)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.BackButton = QtWidgets.QPushButton(FinishWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.gridLayout.addWidget(self.BackButton, 1, 2, 1, 1)
        self.OpenVideoButton = QtWidgets.QPushButton(FinishWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.OpenVideoButton.setFont(font)
        self.OpenVideoButton.setObjectName("OpenVideoButton")
        self.gridLayout.addWidget(self.OpenVideoButton, 1, 1, 1, 1)
        self.QuitButton = QtWidgets.QPushButton(FinishWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.QuitButton.setFont(font)
        self.QuitButton.setObjectName("QuitButton")
        self.gridLayout.addWidget(self.QuitButton, 1, 3, 1, 1)
        self.SuccessLabel = QtWidgets.QLabel(FinishWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.SuccessLabel.setFont(font)
        self.SuccessLabel.setObjectName("SuccessLabel")
        self.gridLayout.addWidget(self.SuccessLabel, 0, 0, 1, 4)

        self.retranslateUi(FinishWindow)
        QtCore.QMetaObject.connectSlotsByName(FinishWindow)

    def retranslateUi(self, FinishWindow):
        _translate = QtCore.QCoreApplication.translate
        FinishWindow.setWindowTitle(_translate("FinishWindow", "Success"))
        self.BackButton.setText(_translate("FinishWindow", "返回主界面"))
        self.OpenVideoButton.setText(_translate("FinishWindow", "打开视频"))
        self.QuitButton.setText(_translate("FinishWindow", "退出"))
        self.SuccessLabel.setText(_translate("FinishWindow", "  视频合成成功！"))
